name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore JellyfinRemoteDownload.csproj

      - name: Build
        run: dotnet build JellyfinRemoteDownload.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish JellyfinRemoteDownload.csproj --configuration Release --output ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JellyfinRemoteDownload
          path: ./publish

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
